//
// V1CurrentJsonGet200ResponseCurrentCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct V1CurrentJsonGet200ResponseCurrentCondition: Codable, JSONEncodable, Hashable {

    public var code: Int?
    public var icon: String?
    public var text: String?

    public init(code: Int? = nil, icon: String? = nil, text: String? = nil) {
        self.code = code
        self.icon = icon
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case icon
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(icon, forKey: .icon)
        try container.encodeIfPresent(text, forKey: .text)
    }
}

